export const groupOf8GeneralPrograms: Record<string, string> = {
    'University of Melbourne (UniMelb)': 'Arts & Humanities; Business, Commerce & Economics; Engineering; Computer Science & Information Systems; Architecture, Building & Planning; Education & Teaching; Law; Medicine; Dentistry & Oral Health; Nursing; Physiotherapy, Occupational Therapy & Allied Health; Psychology; Biomedical Science; Science (Biological, Chemical, Physical & Mathematical Sciences); Agriculture & Veterinary Science; Music, Fine Arts & Performing Arts',
    'UNSW Sydney': 'Business & Commerce; Economics; Aviation; Accounting & Finance; Engineering (Civil, Mechanical, Electrical, Chemical, Software); Computer Science & Information Technology; Data Science & Artificial Intelligence; Architecture & Built Environment; Law & Legal Studies; Medicine; Public Health; Nursing; Biomedical Science; Psychology; Science (Biological, Chemical, Physical & Mathematical Sciences); Education; Arts, Design & Media; Social Sciences & Policy',
    'University of Sydney (USYD)': 'Arts & Humanities; Business, Commerce & Economics; Engineering; Computer Science & Information Systems; Architecture, Building & Planning; Education & Teaching; Law; Medicine & Health Sciences; Nursing & Allied Health; Psychology & Social Sciences; Biomedical & Health Sciences; Science (Biological, Chemical, Physical & Mathematical); Communication & Media; Environmental & Sustainability Studies; Music, Fine Arts & Performing Arts; Veterinary & Agricultural Science; Pathways & Foundation Programs',
    'Monash University': 'Arts & Humanities; Business, Commerce & Economics; Communication, Media & Creative Industries; Design, Architecture & Planning; Engineering; Computer Science & Information Systems; Science (Biological, Chemical, Physical & Mathematical); Health & Medical Sciences; Medicine; Pharmacy & Pharmaceutical Sciences; Nursing & Allied Health; Law; Psychology; Environmental & Sustainability Studies; Music, Fine Arts & Performing Arts; Education & Teaching; Data Science & Analytics; Pathways & Foundation Programs',
    'University of Queensland (UQ)': 'Arts & Humanities; Business, Commerce & Economics; Law; Engineering; Computer Science & Information Systems; Architecture, Building & Planning; Education & Teaching; Medicine & Health Sciences; Nursing & Allied Health; Science (Biological, Chemical, Physical & Mathematical); Psychology & Social Sciences; Agriculture & Animal Sciences; Environmental & Sustainability Studies; Communication & Media; Pathways & Foundation Programs',
    'University of Western Australia (UWA)': 'Arts & Humanities; Business, Commerce & Economics; Law; Engineering; Computer Science & Information Systems; Architecture, Building & Planning; Education & Teaching; Medicine & Health Sciences; Nursing & Allied Health; Science (Biological, Chemical, Physical & Mathematical); Psychology & Social Sciences; Environmental & Earth Sciences; Music, Fine Arts & Performing Arts; Agriculture & Veterinary Science; Pathways & Foundation Program',
    'Adelaide University (AU)': 'Arts & Humanities; Business, Commerce & Economics; Law & Justice; Engineering; Computer Science & Information Systems; Architecture, Building & Planning; Education & Teaching; Medicine, Dentistry & Oral Health; Nursing & Midwifery & Allied Health; Psychology & Social Sciences; Biomedical & Health Sciences; Science (Biological, Chemical, Physical & Mathematical); Agriculture, Animal & Veterinary Science; Environmental & Sustainability Studies; Creative, Media & Communication; Music, Fine Arts & Performing Arts; Tourism, Sport & Events; Nutrition & Food Science; Property, Construction & Real Estate',
    'Australian National University (ANU)': 'Arts & Humanities; Business, Commerce & Economics; Law & Legal Studies; Engineering; Computer Science & Information Systems; Science (Biological, Physical & Mathematical); Government, Public Policy & International Relations; Social Sciences & Psychology; Health & Medical Sciences; Environmental & Earth Sciences; Communication & Media; Creative & Performing Arts; Education & Teaching; Data Science & Analytics; Pathways & Foundation Programs',
};

export const groupOf8PopularPrograms: Record<string, string> = {
    'University of Melbourne (UniMelb)': 'Medicine & Health Sciences; Law; Business & Economics; Engineering; Biomedical Science; Education & Teaching',
    'UNSW Sydney': 'Engineering; Computer Science, Data Science & Artificial Intelligence; Business & Commerce; Law; Medicine & Biomedical Science',
    'University of Sydney (USYD)': 'Medicine & Health Sciences; Law & Legal Studies; Business & Management; Engineering & Technology; Science & Research; Arts & Humanities; Veterinary Science; Environmental & Sustainability Studies; Communication & Media & Creative Arts',
    'Monash University': 'Pharmacy & Pharmacology; Medicine & Health Sciences; Engineering & Technology; Business & Management; Science & Research; Arts & Humanities; Information Technology & Data Science; Law & Legal Studies; Environmental & Sustainability Studies',
    'University of Queensland (UQ)': 'Medicine & Health Sciences; Engineering & Technology; Business & Economics; Science & Research; Agriculture & Animal Sciences; Law; Environmental & Sustainability Studies; Computer Science & IT; Biomedical & Clinical Sciences',
    'University of Western Australia (UWA)': 'Engineering & Technology (especially Mineral & Mining / Civil & Structural); Medicine & Health Sciences; Natural & Environmental Sciences; Business & Management (including MBA excellence); Law & Legal Studies; Arts & Humanities; Computer Science & IT (research & applications',
    'Adelaide University (AU)': 'Medicine & Health Sciences; Engineering & Technology; Business & Management; Law & Legal Studies; Computer Science & IT & Data Science; Agriculture & Veterinary Sciences; Environmental & Sustainability Studies; Biomedical & Health Sciences; Creative & Communication Industries; Tourism & Events Management',
    'Australian National University (ANU)': 'Public Policy & Governance; International Relations & Global Affairs; Science & Research Excellence (Physics, Biology, Chemistry); Law & Legal Studies; Economics & Business; Computing & Cybernetics; Environmental & Sustainability Studies; Health & Medical Sciences; Arts & Humanities & Social Sciences',
};