
import type { SchoolTableEntry } from './schools';
import { schoolLogos } from './logos';

export const canadaSchoolData: SchoolTableEntry[] = [
  {
    university: 'Acsenda School of Management (ASM)',
    logoUrl: schoolLogos['Acsenda School of Management (ASM)'],
    location: ['British Columbia'],
    intakes: 'Jan, Apr, Jul',
    generalPrograms: '',
    popularPrograms: '',
    priorityLevel: 'Low',
    website: 'https://acsenda.com/',
    category: 'Canada Schools',
  },
  {
    university: 'Arbutus College',
    logoUrl: schoolLogos['Arbutus College'],
    location: ['British Columbia'],
    intakes: 'Jan, Apr, May, Jun, Sep',
    generalPrograms: '',
    popularPrograms: '',
    priorityLevel: 'Low',
    website: 'https://arbutuscollege.com/',
    category: 'Canada Schools',
  },
  {
    university: 'Algoma University',
    logoUrl: schoolLogos['Algoma University'],
    location: ['Ontario'],
    intakes: 'Jan, May, Sep',
    generalPrograms: '',
    popularPrograms: '',
    priorityLevel: 'Low',
    website: 'https://algomau.ca/',
    category: 'Canada Schools',
  },
  {
    university: 'Algonquin College',
    logoUrl: schoolLogos['Algonquin College'],
    location: ['Ontario'],
    intakes: 'Jan, May, Sep',
    generalPrograms: '',
    popularPrograms: '',
    priorityLevel: 'Low',
    website: 'https://www.algonquincollege.com/',
    category: 'Canada Schools',
  },
  {
    university: 'Centennial College',
    logoUrl: schoolLogos['Centennial College'],
    location: ['Ontario'],
    intakes: 'Jan, May, Sep',
    generalPrograms: '',
    popularPrograms: '',
    priorityLevel: 'High',
    website: 'https://www.centennialcollege.ca/',
    category: 'Canada Schools',
  },
  {
    university: 'Conestoga College',
    logoUrl: schoolLogos['Conestoga College'],
    location: ['Ontario'],
    intakes: 'Jan, May, Sep',
    generalPrograms: '',
    popularPrograms: '',
    priorityLevel: 'High',
    website: 'https://www.conestogac.on.ca/',
    category: 'Canada Schools',
  },
  {
    university: 'Humber Polytechnic',
    logoUrl: schoolLogos['Humber Polytechnic'],
    location: ['Ontario'],
    intakes: 'Jan, May, Sep',
    generalPrograms: '',
    popularPrograms: '',
    priorityLevel: 'High',
    website: 'https://humber.ca/',
    category: 'Canada Schools',
  },
  {
    university: 'Justice Institute of British Columbia (JIBC)',
    logoUrl: schoolLogos['Justice Institute of British Columbia (JIBC)'],
    location: ['British Columbia'],
    intakes: 'Jan, May, Sep',
    generalPrograms: '',
    popularPrograms: '',
    priorityLevel: 'Low',
    website: 'https://www.jibc.ca/',
    category: 'Canada Schools',
  },
  {
    university: 'Loyalist College',
    logoUrl: schoolLogos['Loyalist College'],
    location: ['Ontario'],
    intakes: 'Jan, May, Sep',
    generalPrograms: '',
    popularPrograms: '',
    priorityLevel: 'High',
    website: 'https://loyalistcollege.com/',
    category: 'Canada Schools',
  },
  {
    university: 'Niagara College',
    logoUrl: schoolLogos['Niagara College'],
    location: ['Ontario'],
    intakes: 'Jan, May, Sep',
    generalPrograms: '',
    popularPrograms: '',
    priorityLevel: 'High',
    website: 'https://www.niagaracollege.ca/',
    category: 'Canada Schools',
  },
  {
    university: 'NorQuest College',
    logoUrl: schoolLogos['NorQuest College'],
    location: ['Alberta'],
    intakes: 'Jan, May, Sep',
    generalPrograms: '',
    popularPrograms: '',
    priorityLevel: 'High',
    website: 'https://www.norquest.ca/',
    category: 'Canada Schools',
  },
  {
    university: 'Northern Lights College (NLC)',
    logoUrl: schoolLogos['Northern Lights College (NLC)'],
    location: ['British Columbia'],
    intakes: 'Jan, May, Sep',
    generalPrograms: '',
    popularPrograms: '',
    priorityLevel: 'High',
    website: 'https://nlc.bc.ca/',
    category: 'Canada Schools',
  },
  {
    university: 'Red River College Polytech (RRC Polytech)',
    logoUrl: schoolLogos['Red River College Polytech (RRC Polytech)'],
    location: ['Manitoba'],
    intakes: 'Jan, May, Sep',
    generalPrograms: '',
    popularPrograms: '',
    priorityLevel: 'High',
    website: 'https://www.rrc.ca/',
    category: 'Canada Schools',
  },
  {
    university: 'Saskatchewan Polytechnic (SASPOLY)',
    logoUrl: schoolLogos['Saskatchewan Polytechnic (SASPOLY)'],
    location: ['Saskatchewan'],
    intakes: 'Jan, May, Sep',
    generalPrograms: '',
    popularPrograms: '',
    priorityLevel: 'High',
    website: 'https://saskpolytech.ca/',
    category: 'Canada Schools',
  },
  {
    university: 'University of British Columbia (UBC) - Okanagan',
    logoUrl: schoolLogos['University of British Columbia (UBC) - Okanagan'],
    location: ['British Columbia'],
    intakes: 'Jan, May, Sep',
    generalPrograms: '',
    popularPrograms: '',
    priorityLevel: 'High',
    website: 'https://ok.ubc.ca/',
    category: 'Canada Schools',
  },
  {
    university: 'University of Calgary (UCalgary)',
    logoUrl: schoolLogos['University of Calgary (UCalgary)'],
    location: ['Alberta'],
    intakes: 'Jan, May, Sep',
    generalPrograms: '',
    popularPrograms: '',
    priorityLevel: 'High',
    website: 'https://www.ucalgary.ca/',
    category: 'Canada Schools',
  },
  {
    university: 'University of Canada West (UCW)',
    logoUrl: schoolLogos['University of Canada West (UCW)'],
    location: ['British Columbia'],
    intakes: 'Jan, Apr, Jul, Sep',
    generalPrograms: '',
    popularPrograms: '',
    priorityLevel: 'High',
    website: 'https://www.ucanwest.ca/',
    category: 'Canada Schools',
  },
  {
    university: 'University of Niagara Falls Canada (UNF)',
    logoUrl: schoolLogos['University of Niagara Falls Canada (UNF)'],
    location: ['Ontario'],
    intakes: 'Jan, Apr, Jul, Oct',
    generalPrograms: '',
    popularPrograms: '',
    priorityLevel: 'High',
    website: 'https://www.unfc.ca/',
    category: 'Canada Schools',
  }
];
