import type { SchoolTableEntry } from './schools';

export const newZealandSchoolData: SchoolTableEntry[] = [
  {
    university: 'Ara Institute of Canterbury (ARA)',
    logoUrl: '',
    location: ['Christchurch'],
    intakes: 'Feb, Jul',
    generalPrograms: 'Business, Commerce & Management; Engineering & Construction Trades; Computer Science & IT; Science & Applied Science; Health & Medical Sciences; Nursing & Allied Health; Hospitality, Tourism & Events; Creative Arts & Design; Media, Broadcasting & Communication; Architecture & Built Environment; Sport, Outdoor & Sustainability Education; Language & Foundation Studies; Certificates, Diplomas & Degrees',
    popularPrograms: 'Applied Management & Business; Engineering & Construction Technology; Health Sciences (Health Promotion, Nutrition, Sport & Exercise Science); Creative Arts & Design; Media, Broadcasting & Communication; Hospitality & Tourism Management; Science & Applied Technology; Outdoor & Sustainability Education; Information Technology & Digital Skill',
    priorityLevel: 'Low',
    website: 'https://www.ara.ac.nz/',
    category: 'New Zealand Schools',
  },
  {
    university: 'Auckland Institute of Studies (AIS)',
    logoUrl: '',
    location: ['Auckland'],
    intakes: 'Feb, May, Sep',
    generalPrograms: 'Business, Commerce & Management; Information Technology & Computer Science; Hospitality & Tourism Management; English Language & Academic Preparation; Communication & Business English; Tourism & Travel; Applied IT & Technical Support; Postgraduate Business & IT',
    popularPrograms: 'Business Administration & Management (incl. BBus & MBA); Information Technology & IT Project Practice; Hospitality & Tourism Management; English Language & IELTS/EAP Preparation; Graduate & Postgraduate Diplomas in Business & IT; Master of Business Administration (MBA); Master of Information Technology (MIT)',
    priorityLevel: 'Low',
    website: 'https://www.ais.ac.nz/',
    category: 'New Zealand Schools',
  },
  {
    university: 'Auckland University of Technology (AUT)',
    logoUrl: '',
    location: ['Auckland'],
    intakes: 'Feb, July',
    generalPrograms: 'Arts & Humanities; Business, Commerce & Economics; Communication & Media; Design & Creative Technologies; Engineering; Computer Science & Information Systems; Science (Biological, Physical & Mathematical); Health & Medical Sciences; Nursing & Allied Health; Education & Teaching; Hospitality, Tourism & Events; Law & Cultural Studies; Māori & Indigenous Development; Sport & Recreation',
    popularPrograms: 'Business & Management; Engineering & Technology; Health & Medical Sciences (incl. Nursing & Physiotherapy); Communication, Media & Creative Technologies; Hospitality & Tourism Management; Information Technology & Digital Innovation; Science & Applied Research; Māori & Indigenous Development; Public Policy & Social Sciences',
    priorityLevel: 'Low',
    website: 'https://www.aut.ac.nz/',
    category: 'New Zealand Schools',
  },
  {
    university: 'ICL Graduate Business School',
    logoUrl: '',
    location: ['Auckland'],
    intakes: 'Jan, Mar, May, Jul, Aug, Sep, Nov',
    generalPrograms: 'Business, Commerce & Management; Business Informatics & IT; Early Childhood Education; Diploma, Bachelor’s, Graduate & Postgraduate Studies (Business & Related Fields)',
    popularPrograms: 'Master of Management; Master of Business Informatics; Graduate Diploma in Business; Bachelor’s Degrees in Business & Business Informatics; Graduate Diploma in Teaching (ECE)',
    priorityLevel: 'Low',
    website: 'https://icl.ac.nz/',
    category: 'New Zealand Schools',
  },
  {
    university: 'Massey University',
    logoUrl: '',
    location: ['Auckland'],
    intakes: 'May, Oct',
    generalPrograms: 'Arts & Humanities; Business, Commerce & Economics; Law & Social Sciences; Engineering & Technology; Computer Science & Information Systems; Science (Biological, Earth & Physical); Health & Medical Sciences; Veterinary & Animal Sciences; Agriculture & Environmental Studies; Aviation & Aerospace Studies; Design, Creative & Communication Arts; Education & Teaching; Māori & Indigenous Studies; Pathway & Foundation Programs',
    popularPrograms: 'Veterinary Science (highly ranked globally); Aviation & Air Transport; Agriculture & AgriScience; Food Technology & Applied Science; Business & Management; Engineering & Technology; Creative Arts & Design; Environmental & Sustainability Sciences; Health, Nursing & Allied Health; Communication & Media',
    priorityLevel: 'Low',
    website: 'https://www.massey.ac.nz/',
    category: 'New Zealand Schools',
  },
  {
    university: 'Unitec Institute of Technology',
    logoUrl: '',
    location: ['Auckland'],
    intakes: 'Feb, Jul',
    generalPrograms: 'Arts & Humanities; Business, Commerce & Management; Communication & Media; Computer Science & Information Systems; Engineering & Construction; Design & Visual Arts; Architecture & Landscape; Health & Medical Sciences; Nursing & Allied Health; Early Childhood & Education Studies; Science & Applied Science; Trades & Technical Programs; Environmental & Animal Sciences; Language & Foundation Studies; Pathway & Certificate Programs (certificates–masters',
    popularPrograms: 'Applied Business & Management; Engineering & Technology (Civil, Electrical, Automotive); Health & Medical Sciences (Nursing, Medical Imaging); Computing & IT (Software, Networks, Cybersecurity); Architecture, Design & Creative Arts; Construction Management & Property Development; Social Practice & Community Development; Veterinary & Animal Health; Sport, Exercise & Recreation',
    priorityLevel: 'Low',
    website: 'https://www.unitec.ac.nz/',
    category: 'New Zealand Schools',
  },
  {
    university: 'University of Waikato',
    logoUrl: '',
    location: ['Hamilton', 'Tauranga'],
    intakes: 'Mar, Jul, Nov',
    generalPrograms: 'Arts & Humanities; Business, Commerce & Economics; Law; Engineering; Computer Science & Information Systems; Science (Biological, Physical & Mathematical); Health & Medical Sciences; Education & Teaching; Māori & Indigenous Studies; Social Sciences & Psychology; Environmental & Natural Sciences; Communication & Media; Sport & Human Movement; Technology & Mathematics; Pathways & Foundation Programs',
    popularPrograms: 'Business & Management (Waikato Management School – Triple Crown AACSB/EQUIS/AMBA); Engineering & Technology; Computer Science & IT; Health & Nursing; Education & Teaching; Māori & Indigenous Studies; Environmental & Sustainability Sciences; Law & Social Sciences',
    priorityLevel: 'Low',
    website: 'https://www.waikato.ac.nz/int/',
    category: 'New Zealand Schools',
  },
  {
    university: 'University of Auckland',
    logoUrl: '',
    location: ['Auckland'],
    intakes: 'Feb, Jul',
    generalPrograms: 'Arts & Humanities; Business, Commerce & Economics; Law & Justice; Engineering; Computer Science & Information Systems; Health, Medicine & Biomedical Sciences; Nursing & Allied Health; Science (Biological, Physical & Mathematical); Education & Teaching; Communication, Media & Creative Arts; Architecture, Design & Planning; Māori & Indigenous Studies; Environmental & Sustainability Sciences; Technology & Innovation; Mathematics & Statistics',
    popularPrograms: 'Law & Legal Studies (ranked globally high); Engineering & Technology; Business & Management (Triple Crown-style research & reputation); Health & Medical Sciences; Science & Research Excellence; Arts & Humanities; Māori & Indigenous Development; Marine & Environmental Sciences; Communication & Creative Arts; Computer Science & IT',
    priorityLevel: 'Low',
    website: 'https://international.auckland.ac.nz/',
    category: 'New Zealand Schools',
  },
];
