export const SEARCH_CONFIG = {
  enabled: process.env.BRAVE_SEARCH_ENABLED !== 'false',
  count: parseInt(process.env.BRAVE_SEARCH_COUNT || '5', 10),
  safesearch: (process.env.BRAVE_SEARCH_SAFESEARCH || 'moderate') as 'off' | 'moderate' | 'strict',
  country: process.env.BRAVE_SEARCH_COUNTRY || 'PH',
  triggerKeywords: [
    'search',
    'find',
    'look up',
    'what is',
    'who is',
    'how to',
    'latest',
    'current',
    'news',
    'update',
    'price',
    'cost',
    'requirement',
    'visa',
    'scholarship',
    'deadline',
    'intake',
    'admission',
    'tuition',
    'fee',
    'ielts',
    'pte',
    'toefl',
  ],
  priorityDomains: [
    'edu.au',
    'edu.ph',
    'gov.au',
    'gov.ph',
    'studyinaustralia.gov.au',
    'homeaffairs.gov.au',
    'immi.homeaffairs.gov.au',
    'studynavi.example.com',
  ],
  excludeDomains: [
    'facebook.com',
    'twitter.com',
    'instagram.com',
    'tiktok.com',
  ],
};

export const SEARCH_CACHE_TTL_MS = parseInt(
  process.env.BRAVE_SEARCH_CACHE_TTL_MS || String(15 * 60 * 1000),
  10,
);

export const SMALLTALK_PATTERN = /^(hi|hello|thanks|ok|test)\b/i;

export const FACTUAL_RISK_PATTERNS = [
  /\bvisa\b/i,
  /\bsubclass\b/i,
  /\bimmigration\b/i,
  /\bpolicy\b/i,
  /\brule(s)?\b/i,
  /\bregulation(s)?\b/i,
  /\brequirement(s)?\b/i,
  /\beligib(le|ility)\b/i,
  /\bdeadline(s)?\b/i,
  /\bintake(s)?\b/i,
  /\bfee(s)?\b/i,
  /\bcost(s)?\b/i,
  /\btuition\b/i,
  /\bprocessing time(s)?\b/i,
  /\bquota\b|\bcap\b/i,
  /\bOSHC\b|\boverseas student health cover\b|\bhealth insurance\b/i,
  /\binsurance\b/i,
  /\bbiometrics\b/i,
  /\bmedical\b|\bhealth exam\b/i,
  /\bGTE\b|\bGS\b|\bGenuine Student\b/i,
  /\bCoE\b|\bconfirmation of enrolment\b/i,
  /\bwork rights?\b|\bwork hours?\b|\bpost[- ]study work\b/i,
  /\bfinancial requirement(s)?\b|\bproof of funds\b|\bshow money\b|\bfunds\b/i,
  /\bapplication fee\b|\bvisa fee\b/i,
  /\benglish test\b|\btest score\b/i,
  /\bielts\b|\btoefl\b|\bpte\b|\bduolingo\b/i,
  /\bpolicy date\b|\beffective\b|\bas of\b/i,
  /\bupdated\b|\blatest\b|\bcurrent\b/i,
  /\b202[5-6]\b/i,
];

export const RECENCY_TOPIC_PATTERNS = [
  /\bvisa\b/i,
  /\bsubclass\b/i,
  /\bimmigration\b/i,
  /\bpolicy\b/i,
  /\brule(s)?\b/i,
  /\bregulation(s)?\b/i,
  /\brequirement(s)?\b/i,
  /\bdeadline(s)?\b/i,
  /\bintake(s)?\b/i,
  /\bfee(s)?\b/i,
  /\bcost(s)?\b/i,
  /\btuition\b/i,
  /\bprocessing time(s)?\b/i,
  /\bquota\b|\bcap\b/i,
  /\bOSHC\b|\boverseas student health cover\b|\bhealth insurance\b/i,
  /\bwork rights?\b|\bwork hours?\b|\bpost[- ]study work\b/i,
  /\bfinancial requirement(s)?\b|\bproof of funds\b|\bshow money\b/i,
  /\bapplication fee\b|\bvisa fee\b/i,
  /\benglish test\b|\btest score\b/i,
  /\bielts\b|\btoefl\b|\bpte\b|\bduolingo\b/i,
];

export const RECENCY_SIGNAL_PATTERNS = [
  /\blatest\b/i,
  /\bcurrent\b/i,
  /\bupdated?\b/i,
  /\bupdate\b/i,
  /\beffective\b|\bas of\b/i,
  /\b202[5-6]\b/i,
  /\bthis year\b|\bnext year\b/i,
];
