'use client';

import { ArrowRight, Plane, Shield } from 'lucide-react';
import type { VisaProcessStep } from '@/components/study/cards/visa-process-card.types';

interface VisaProcessCardMiniViewProps {
  steps: VisaProcessStep[];
  isNewZealand: boolean;
  isCanada: boolean;
}

export function VisaProcessCardMiniView({
  steps,
  isNewZealand,
  isCanada,
}: VisaProcessCardMiniViewProps) {
  return (
    <div className="w-full">
      <h3 className="flex items-center gap-2 text-base font-bold text-[#004097] text-center justify-center">
        <Plane className="h-4 w-4 text-yellow-500" />
        Student Visa Process Flow
      </h3>
      <div className="relative mt-4">
        <div className="grid grid-cols-1 sm:grid-cols-2 gap-x-8">
          <div className="space-y-3">
            {steps.slice(0, Math.ceil(steps.length / 2)).map((step, index) => (
              <div key={index}>
                <h3 className="text-xs font-bold text-[#004097]">
                  {index + 1}
                  .&nbsp;
                  {step.title}
                </h3>
                <p className="text-[10px] text-gray-600 pl-4">{step.description}</p>
              </div>
            ))}
          </div>
          <div className="space-y-3 mt-3 sm:mt-0">
            {steps.slice(Math.ceil(steps.length / 2)).map((step, index) => {
              const stepNumber = index + Math.ceil(steps.length / 2) + 1;
              if (step.isBranch) {
                return (
                  <div key={index}>
                    <h3 className="text-xs font-bold text-[#004097]">
                      {stepNumber}
                      .&nbsp;
                      {step.title}
                    </h3>
                    <div className="pl-4 space-y-1 mt-1 text-[10px]">
                      <div className="flex items-start gap-2">
                        <span className="font-medium text-green-700">Visa Granted</span>
                        <ArrowRight className="h-3 w-3 text-gray-400 mt-0.5" />
                        {isNewZealand && (
                          <div className="flex flex-col text-gray-600">
                            <span>Approval in Principle (AIP)</span>
                            <span>Pre-Departure Orientation</span>
                          </div>
                        )}
                        {isCanada && (
                          <div className="flex flex-col text-gray-600">
                            <span>Passport Submission Request</span>
                            <span>POE Introduction Letter</span>
                            <span>Pre-Departure Orientation</span>
                          </div>
                        )}
                        {!isNewZealand && !isCanada && (
                          <span className="text-gray-600">Pre-Departure Orientation</span>
                        )}
                      </div>
                      <div className="flex items-center gap-2">
                        <span className="font-medium text-red-700">Visa Refused</span>
                        <ArrowRight className="h-3 w-3 text-gray-400" />
                        <span className="text-gray-600">Refund Assistance</span>
                      </div>
                    </div>
                  </div>
                );
              }

              return (
                <div key={index}>
                  <h3 className="text-xs font-bold text-[#004097]">
                    {stepNumber}
                    .&nbsp;
                    {step.title}
                  </h3>
                  <p className="text-[10px] text-gray-600 pl-4">{step.description}</p>
                </div>
              );
            })}
          </div>
        </div>
      </div>

      <div className="mt-6 rounded-xl bg-blue-50 p-4 border border-blue-100 text-blue-800 flex items-center gap-3">
        <div className="w-full">
          <p className="font-bold mb-1 flex items-center justify-center gap-2 text-sm" style={{ color: 'crimson' }}>
            <Shield className="h-4 w-4" style={{ color: 'crimson' }} />
            Privacy Disclosure:
          </p>
          <p className="text-xs text-justify">
            This is an <strong>internal document</strong> generated by StudyNavi and is <strong>not meant to be shared</strong> with anyone other than the <strong>student that has been consulted</strong>. <strong>Unauthorized distribution</strong> of this document is <strong>strictly prohibited</strong> and is subject to the <strong>full extent of the law</strong> under the <strong>Republic Act No. 10173</strong>, also known as the <strong>Data Privacy Act of 2012 (DPA)</strong>.
          </p>
        </div>
      </div>
    </div>
  );
}
